name: Code Check on Push

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure you're using the correct version of Node.js

      - name: Clear npm cache
        run: npm cache clean --force  # Cleans the npm cache to prevent installation issues

      - name: Install dependencies
        run: npm install  # Installs project dependencies from package.json

      - name: Run build (optional)
        run: npm run build  # Optional: run build if defined in package.json

      - name: Run tests (if available)
        run: npm test || echo "No tests found"  # Run tests or print a message if no tests are defined
